// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbrmxFSqj60xVQCwDYtfyDVXk6whiDaX4',
    appId: '1:870778353149:web:0bf76bad30d860bd821594',
    messagingSenderId: '870778353149',
    projectId: 'chat-project-37e6e',
    authDomain: 'chat-project-37e6e.firebaseapp.com',
    storageBucket: 'chat-project-37e6e.appspot.com',
    measurementId: 'G-D09Y70Q9C6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5w6E0P57R0_rAIp2sVRunkWL4ZeYE-QQ',
    appId: '1:870778353149:android:f133269e21087f22821594',
    messagingSenderId: '870778353149',
    projectId: 'chat-project-37e6e',
    storageBucket: 'chat-project-37e6e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB337_-vrVlBgajGTviCu57i7w1ry75mUE',
    appId: '1:870778353149:ios:4aa690c2a615ba08821594',
    messagingSenderId: '870778353149',
    projectId: 'chat-project-37e6e',
    storageBucket: 'chat-project-37e6e.appspot.com',
    iosBundleId: 'com.example.testChat',
  );
}
